
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int DISPLAY = 9;
  public static final int OP_NE = 28;
  public static final int OP_GT = 20;
  public static final int OP_NOT = 29;
  public static final int OP_AND = 30;
  public static final int FOR = 14;
  public static final int OP_MULTI = 26;
  public static final int IDENTIFICADOR = 40;
  public static final int CONSTANTE_ENTERA = 2;
  public static final int GET = 10;
  public static final int NEXT = 15;
  public static final int IF = 5;
  public static final int ENDWHILE = 19;
  public static final int DIM = 8;
  public static final int EOF = 0;
  public static final int STRING_TYPE = 13;
  public static final int OP_DIVISION = 27;
  public static final int OP_GTE = 22;
  public static final int error = 1;
  public static final int OP_LT = 21;
  public static final int COMA = 35;
  public static final int OP_TIPO = 34;
  public static final int OP_OR = 31;
  public static final int INTEGER_TYPE = 11;
  public static final int OP_MINUS = 25;
  public static final int CORCHETE_CLOSE = 39;
  public static final int ENDIF = 18;
  public static final int ELSE = 6;
  public static final int TO = 16;
  public static final int WHILE = 7;
  public static final int OP_EQ = 33;
  public static final int LONG = 17;
  public static final int PAREN_CLOSE = 37;
  public static final int CONSTANTE_STRING = 4;
  public static final int OP_PLUS = 24;
  public static final int FLOAT_TYPE = 12;
  public static final int OP_LTE = 23;
  public static final int CORCHETE_OPEN = 38;
  public static final int CONSTANTE_FLOAT = 3;
  public static final int OP_ASIG = 32;
  public static final int PAREN_OPEN = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONSTANTE_ENTERA",
  "CONSTANTE_FLOAT",
  "CONSTANTE_STRING",
  "IF",
  "ELSE",
  "WHILE",
  "DIM",
  "DISPLAY",
  "GET",
  "INTEGER_TYPE",
  "FLOAT_TYPE",
  "STRING_TYPE",
  "FOR",
  "NEXT",
  "TO",
  "LONG",
  "ENDIF",
  "ENDWHILE",
  "OP_GT",
  "OP_LT",
  "OP_GTE",
  "OP_LTE",
  "OP_PLUS",
  "OP_MINUS",
  "OP_MULTI",
  "OP_DIVISION",
  "OP_NE",
  "OP_NOT",
  "OP_AND",
  "OP_OR",
  "OP_ASIG",
  "OP_EQ",
  "OP_TIPO",
  "COMA",
  "PAREN_OPEN",
  "PAREN_CLOSE",
  "CORCHETE_OPEN",
  "CORCHETE_CLOSE",
  "IDENTIFICADOR"
  };
}

